Ink/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView, TemplateView
from django.conf.urls.static import static


urlpatterns = [
	
    # Main Urls
    path('', LoginView.as_view(template_name='Ink/login.html'), name="login"),
    path('register', views.register, name='register'),
    path('home', views.home, name='home'),
    path('company', views.company, name='company'),
    path('profile', views.profile, name='profile'),
    path('createComp', views.createComp, name='createComp'),
    path('compHome/<cmp_id>', views.compHome, name='compHome'),
    path('ownComp', views.ownComp, name='ownComp'),
    path('join/<companyName>', views.join, name='join'), 
    path('leave/<companyName>', views.leave, name='leave'), 
    path('employee', views.employee, name='employee'),
    path('type/<username>', views.type, name='type'),
    path('logout', LogoutView.as_view(template_name='Ink/logout.html'), name="logout"),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InkredoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from Ink.urls import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ink.urls')),
]

Ink/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.conf import settings
import uuid

#Type of user
class CompOrEmp(models.Model):
	
	#2 Types of users
	TYPE=(
		("employee", ("employee")),
		("company", ("company"))
		)
	name=models.ForeignKey(User, on_delete=models.CASCADE)
	typ=models.CharField(max_length=50, choices=TYPE)


#Company Details with user obj as a foreign key linking user account with user details
class Company(models.Model):
	company=models.ForeignKey(User, on_delete=models.CASCADE)
	cmp_id=models.CharField(max_length=1000,primary_key=True)
	image=models.ImageField(upload_to='pictures', blank=True)
	created=models.DateTimeField(auto_now=True)


#Employee Details with user obj as a foreign key linking user account with user details
class Employee(models.Model):
	employee=models.ForeignKey(User, on_delete=models.CASCADE)
	emp_id=models.CharField(max_length=1000,primary_key=True)
	image=models.ImageField(upload_to='pictures', blank=True)
	currentCompany= models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True)


#Current employees of a company with employee as a many to many relation
class CompanyEmployee(models.Model):
	cmp_id=models.ForeignKey(Company, on_delete=models.CASCADE)
	currentEmployees= models.ManyToManyField(Employee)


#Employement history of an employee with company as a many to many relation
class EmployementHistory(models.Model):
	emp_id=models.OneToOneField(Employee, on_delete=models.CASCADE, primary_key=True)
	companiesAppliedToHistory= models.ManyToManyField(Company)
	

'''Employement tenure in a company details with repetition allowed for the case if user
worked and then left and then joined again'''
class EmpDate(models.Model):
	id1 = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	cmp_id=models.ForeignKey(Company, on_delete=models.CASCADE)
	emp_id=models.ForeignKey(Employee, on_delete=models.CASCADE,null=True)
	created=models.DateTimeField()
	left=models.DateTimeField(null=True, blank=True)


#Employee creating his own company having the emp_id and cmp_id as the foreign keys
class EmpCompany(models.Model):
	emp_id=models.ForeignKey(Employee, on_delete=models.CASCADE,null=True)
	cmp_id=models.ForeignKey(Company, on_delete=models.CASCADE)

Ink/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .models import *

#Registration Form
class RegistrationForm(UserCreationForm):
    class Meta:
        model= User
        fields=['username','first_name','password1','password2']


#Type of user form
class TypeForm(forms.ModelForm):
	
	#2 Types of users
	TYPE=(
		("employee", ("employee")),
		("company", ("company"))
		)
	typ=forms.ChoiceField(choices=TYPE,required=True)

	class Meta:
		model = CompOrEmp
		fields=['typ']

Ink/views.py
from django.shortcuts import render,redirect
from django.template import loader
from django import forms
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.utils import timezone
from django.contrib.auth.models import User

#Registeration
def register(request):
	if request.method == "POST":
		try:
			form=RegistrationForm(request.POST)
			# If form Is valid
			if form.is_valid():
				form.save()

				#If Logged In Employee Creating A Company
				if(str(request.user) != "AnonymousUser"):

					#Creating A new Company User
					obj2,notif=User.objects.get_or_create(username=request.POST.get('username'), first_name=request.POST.get('first_name'))
					if notif is True:
						obj.save()

					#Selecting the newly created company
					username=User.objects.get(username=request.POST.get('username'))
					obj,notif=CompOrEmp.objects.get_or_create(name=username, typ="company")
					if notif is True:
						obj.save()

					#Creating A Company Object
					userObj=User.objects.get(username=username)
					obj,notif=Company.objects.get_or_create(company=User.objects.filter(Q(username=username))[0], cmp_id=str(userObj.username))
					if notif is True:
						obj.save()

					#Creating Employee Having A company object
					userObj=User.objects.get(username=username)
					obj1,notif=EmpCompany.objects.get_or_create(emp_id=Employee.objects.get(employee=request.user), cmp_id=obj)
					if notif is True:
						obj1.save()

					return HttpResponseRedirect('/createComp')
				
				else:
					url="/type/"+request.POST.get('username')
					return redirect(url, username=request.POST.get('username'))

		except Exception as e:
			section='/register'
			return HttpResponseRedirect(section)
	
	else:
		form=RegistrationForm()
	args = {"form": form}
	return render(request, 'Ink/register.html', args)


#Register if a newly registered User is a Company or an Employee
def type(request, username):
	if(request.method == "POST"):
		try:
			form=TypeForm(request.POST)
			if form.is_valid():
				obj=form.save(commit=False)

				#Creating Company Or Employee Object to store if the new entry is a company or employee
				obj,notif=CompOrEmp.objects.get_or_create(name=User.objects.filter(Q(username=username))[0], typ=request.POST.get('typ'))
				if notif is True:
					obj.save()

				#Creating Company Object if its a company to store company info.
				if(str(request.POST.get('typ'))=="company"):
					userObj=User.objects.get(username=username)
					obj,notif=Company.objects.get_or_create(company=User.objects.filter(Q(username=username))[0], cmp_id=str(userObj.username))

				#Creating Employee Object if its an employee to store company info.
				elif(str(request.POST.get('typ'))=="employee"):
					userObj=User.objects.get(username=username)
					obj,notif=Employee.objects.get_or_create(employee=User.objects.filter(Q(username=username))[0], emp_id=str(userObj.username))
				
				if notif is True:
					obj.save()
				return HttpResponseRedirect('/createComp')

		except Exception as e:
			url="/type/"+username
			return redirect(url, username=username)
	
	else:
		form=TypeForm()
	args = {"form": form ,'username': username}
	return render(request, 'Ink/type.html', args)


#Home
@login_required(login_url='/')
def home(request):
	try:
		filterUser=CompOrEmp.objects.get(name=request.user)
		
		#If logged in user is a company
		if(filterUser.typ == "company"):
			return HttpResponseRedirect('/company')
		else:
			return HttpResponseRedirect('/employee')	
	except:
		return HttpResponseRedirect('/')


#If logged in is an Employee
@login_required(login_url='/')
def employee(request):
	try:
		#Excluding the self created company of the employee
		comp=Company.objects.all().order_by('-created')
		empComp=Company.objects.exclude(cmp_id__in=[item.cmp_id.cmp_id for item in EmpCompany.objects.all()])
		args={"companies": empComp, 'employee': Employee.objects.get(employee=request.user)}

	except Exception as e:
		return HttpResponseRedirect('/home')
	return render(request, 'Ink/companyList.html', args)


#If employee joins a company
@login_required(login_url='/')
def join(request, companyName):

	cmpObj=Company.objects.filter(Q(cmp_id=companyName))
	empObj=Employee.objects.get(employee=request.user)
	empObj.currentCompany=cmpObj[0]
	try:
		#If he has not joined the company before create a new obj

		if(len(EmployementHistory.objects.all()) ==0 or len(EmpDate.objects.filter(Q(emp_id=empObj), Q(cmp_id=cmpObj[0])))==0):
			
			#Employeement History
			obj, notif=EmployementHistory.objects.get_or_create(emp_id=empObj)
			if(notif==True):
				obj.save()
			obj.companiesAppliedToHistory.add(cmpObj[0])
			obj.save()

			#Tenure of working for each company
			obj, notif=EmpDate.objects.get_or_create(cmp_id=cmpObj[0], emp_id=empObj, created=timezone.now(), left=None)
			if(notif==True):
				obj.save()

			#Which company the employee belongs to
			obj, notif=CompanyEmployee.objects.get_or_create(cmp_id=cmpObj[0])
			if(notif==True):
				obj.save()
			obj.currentEmployees.add(empObj)
			obj.save()

		else:
			#If already worked in the company then update the dates of working
			obj=EmployementHistory.objects.get(emp_id=empObj.emp_id)
			obj.companiesAppliedToHistory.add(cmpObj[0])
			obj.save()
			
			obj=EmpDate.objects.filter(Q(cmp_id=cmpObj[0]),Q(emp_id=empObj))
			for i in obj:
				i.left=None
				i.save()

			obj=CompanyEmployee.objects.get(cmp_id=cmpObj[0])
			obj.currentEmployees.add(empObj)
			obj.save()

	except Exception as e:
		
		obj=EmployementHistory.objects.get(emp_id=empObj.emp_id)
		obj.left=None
		obj.companiesAppliedToHistory.add(cmpObj[0])
		obj.save()

		obj=CompanyEmployee.objects.get(cmp_id=cmpObj[0])
		obj.currentEmployees.add(empObj)
		obj.save()

	empObj.save()
	return HttpResponseRedirect('/home')


#If he leaves the company
@login_required(login_url='/')
def leave(request, companyName):

	cmpObj=Company.objects.filter(Q(cmp_id=companyName))
	empObj=Employee.objects.get(employee=request.user)
	empObj.currentCompany= None
	empObj.save()

	obj=CompanyEmployee.objects.get(cmp_id=cmpObj[0])
	obj.currentEmployees.remove(empObj)
	obj.save()

	obj=EmpDate.objects.filter(Q(cmp_id=cmpObj[0])).order_by('-created')
	for i in obj:
		i.left=timezone.now()
		i.save()
		break

	return HttpResponseRedirect('/home')


#Profile
@login_required(login_url='/')
def profile(request):
	obj=CompOrEmp.objects.get(name=request.user)
	
	# If user is a company
	if(obj.typ=="company"):
		args={'company':obj}
		return render(request, 'Ink/compProfile.html', args)
	else:
		args={'history': EmpDate.objects.filter(Q(emp_id=Employee.objects.get(employee=request.user)))}
		return render(request, 'Ink/profile1.html', args)


#If its a company
@login_required(login_url='/')
def company(request):
	cmpObj=Company.objects.all()
	args={'companies': cmpObj}
	return render(request, 'Ink/compHome.html',args)


#Each company's profile
@login_required(login_url='/')
def compHome(request, cmp_id):
	cmpObj=Company.objects.filter(Q(cmp_id=cmp_id))
	
	args={'employed': EmpDate.objects.filter(Q(cmp_id=cmpObj[0])),
	'currDate': timezone.now()}
	return render(request, 'Ink/company1.html', args)


#Company create page
@login_required(login_url='/')
def createComp(request):
	print(request.user)
	obj=EmpCompany.objects.filter(Q(emp_id=Employee.objects.get(employee=request.user)))
	args={'companies': obj}
	return render(request, 'Ink/createComp.html', args)


#Companies made by employee
@login_required(login_url='/')
def ownComp(request):
	obj=EmpCompany.objects.filter(Q(emp_id=Employee.objects.get(employee=request.user)))
	args={'companies': obj}
	return render(request, 'Ink/ownComp.html', args)

Ink/templates/Ink/compHome.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block body %}
<br><br>
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Company Name</th>
      <th scope="col">Company Id</th>
      <th scope="col">Created</th>
    </tr>
  </thead>
  <tbody>
  	{% for i in companies %}
    <tr>
      <td><a href="/compHome/{{i.cmp_id}}"><b>{{i.company.first_name}}</b></a></td>
      <td>{{i.cmp_id}}</td>
      <td>{{ i.created| naturaltime }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<script type="text/javascript">
    var n=document.getElementById('1');
  console.log("yes");
  console.log(n);
  n.innerHTML="Create Company";
  n.setAttribute('href', '/createComp');

  var n=document.getElementById('2');
  console.log("yes");
  console.log(n);
  n.innerHTML="See Your Companies";
  n.setAttribute('href', '/ownComp');
  </script>
{% endblock %}

Ink/templates/Ink/compProfile.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block body %}
  <br><br>
  <div class="card" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px; margin: auto; text-align: center; font-family: arial;">
    <img src="http://robohash.org/sitsequiquia.png?size=120x120" alt="{{company.name.first_name}}" style="width:100%">
    <br>
    <a href="#" class="btn btn-block btn-primary"><span class="glyphicon glyphicon-plus-sign">Upload Picture</span> </a>
    <h1><b>{{company.name.first_name}}</b></h1>
    <p class="title" style="color: grey; font-size: 18px;">Company</p>
    <p><b>{{company.name}}</b></p>

    <p><button class="btn btn-info">Contact</button></p>
  </div>
{% endblock %}

Ink/templates/Ink/company.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href={% static 'Ink/css/company.css' %}>
{% endblock %}
{% block body %}

<section class="container">
  <div class="left-half div1">
    <h1>Present Employees</h1>
      <table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Employee Name</th>
      <th scope="col">Employee Id</th>
    </tr>
  </thead>
  <tbody>
    {% for i in cmpDetail %}
    {% for j in i.currentEmployees.all %}
     
    <tr>
     
     {% for k in date %}

      {% if k.left == None or currDate < k.left %}
      <td>{{j.employee}}</td>
      <td>{{j.emp_id}}</td>
      {% endif %}
      {% endfor %}

    </tr>
    {% endfor %}
    {% endfor %}
  </tbody>
</table>
</div>
  <div class="right-half div1">
    <h1>Past Employees</h1>
      <table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Employee Name</th>
      <th scope="col">Employee Id</th>
    </tr>
  </thead>
  <tbody>
    {% for i in cmpDetail %}
    {% for j in i.currentEmployees.all %}
     
    <tr>
     
     {% for k in date %}

      {% if k.left and currDate > k.left %}
      <td>{{j.employee}}</td>
      <td>{{j.emp_id}}</td>
      {% endif %}
      {% endfor %}

    </tr>
    {% endfor %}
    {% endfor %}
  </tbody>
</table>
  </div>
</section>
	
{% endblock %}

Ink/templates/Ink/company1.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href={% static 'Ink/css/company.css' %}>
{% endblock %}
{% block body %}

<section class="container">
  <div class="left-half div1">
    <pre><b>Present Employees</b></pre>
      <table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Employee Name</th>
      <th scope="col">Employee Id</th>
      <th scope="col">Join Date</th>
      <th scope="col">Left</th>
    </tr>
  </thead>
  <tbody>
    {% for i in employed %}
      {% if i.left == None or currDate < i.left %}
      <td>{{i.emp_id.employee.first_name}}</td>
      <td>{{i.emp_id.emp_id}}</td>
      <td>{{i.created| naturaltime}}</td>
      {% if i.left == None %}
        <td><b>Still Working</b></td>
      {% else %}
        <td>{{i.left| naturaltime}}</td>
      {% endif %}
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
  <div class="right-half div1">
    <pre><b>Past Employees</b></pre>
      <table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Employee Name</th>
      <th scope="col">Employee Id</th>
      <th scope="col">Join Date</th>
      <th scope="col">Left</th>
    </tr>
  </thead>
  <tbody>
    {% for i in employed %}
      {% if currDate > i.left %}
      <td>{{i.emp_id.employee.first_name}}</td>
      <td>{{i.emp_id.emp_id}}</td>
      <td>{{i.created| naturaltime }}</td>
      {% if i.left == None %}
        <td><b>Still Working</b></td>
      {% else %}
        <td>{{i.left| naturaltime}}</td>
      {% endif %}
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
  </div>
</section>
	
{% endblock %}

Ink/templates/Ink/companyList.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block body %}
	<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Company Name</th>
      <th scope="col">Created</th>
      <th scope="col">Join</th>
    </tr>
  </thead>
  <tbody>
  	{% for i in companies %}
    <tr>
      <td>{{i.company.first_name}}</td>
      <td>{{ i.created| naturaltime }}</td>
      {% if employee.currentCompany == None %}
      	<td><a href="/join/{{i.company}}"><button class="btn btn-info">Join</button></a></td>
      {% else %}
      	{% if employee.currentCompany == i %}
      		<td><a href="/leave/{{i.company}}"><button class="btn btn-info">Leave</button></a></td>
      	{% else %}
      		<td><a href="#"><button class="btn btn-info" disabled="">Join</button></a></td>
      	{% endif %}
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
<script type="text/javascript">
    var n=document.getElementById('1');
  console.log("yes");
  console.log(n);
  n.innerHTML="Create Company";
  n.setAttribute('href', '/createComp');

  var n=document.getElementById('2');
  console.log("yes");
  console.log(n);
  n.innerHTML="See Your Companies";
  n.setAttribute('href', '/ownComp');
  </script>
{% endblock %}

Ink/templates/Ink/createComp.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block body %}
  <br><br>
  <div class="card" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px; margin: auto; text-align: center; font-family: arial;">
    <img src="http://robohash.org/sitsequiquia.png?size=120x120" alt="{{company.name.first_name}}" style="width:100%">
    <br>
    <a href="/register" class="btn btn-block btn-primary"><span class="glyphicon glyphicon-plus-sign">Create Company</span> </a>
    <h1><b>{{company.name.first_name}}</b></h1>
    <p class="title" style="color: grey; font-size: 18px;">Company</p>
    <p><b>{{company.name}}</b></p>

    <p><button class="btn btn-info">Contact</button></p>
  </div>
<script type="text/javascript">
    var n=document.getElementById('1');
  console.log("yes");
  console.log(n);
  n.innerHTML="Create Company";
  n.setAttribute('href', '/createComp');

  var n=document.getElementById('2');
  console.log("yes");
  console.log(n);
  n.innerHTML="See Your Companies";
  n.setAttribute('href', '/ownComp');
  </script>
{% endblock %}

Ink/templates/Ink/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
<div class="page-header">
	<h1>Login</h1>
</div>
<div class="col-lg-5">
	<form method="POST" action="">
		{% csrf_token %}
</div>
</form>
{% endblock %}

Ink/templates/Ink/ownComp.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block body %}
<br><br>
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Company Name</th>
      <th scope="col">Company Id</th>
      <th scope="col">Created</th>
    </tr>
  </thead>
  <tbody>
    {% for i in companies %}
    <tr>
      <td><a href="/compHome/{{i.cmp_id.cmp_id}}"><b>{{i.cmp_id.company.first_name}}</b></a></td>
      <td>{{i.cmp_id.cmp_id}}</td>
      <td>{{ i.cmp_id.created| naturaltime }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<script type="text/javascript">
  var n=document.getElementById('1');
  console.log("yes");
  console.log(n);
  n.innerHTML="Create Company";
  n.setAttribute('href', '/createComp');

  var n=document.getElementById('2');
  console.log("yes");
  console.log(n);
  n.innerHTML="See Your Companies";
  n.setAttribute('href', '/ownComp');
</script>
{% endblock %}

Ink/templates/Ink/profile.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block body %}
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Company</th>
      <th scope="col">Joined</th>
      <th scope="col">Left</th>
    </tr>
  </thead>
  <tbody>
  	{% for i in history %}
    {% for j in i.companiesAppliedToHistory.all %}
    <tr>
      <td><a href="/compnayProfile/{{j.company}}">{{j.company}}</a></td>
      {% for k in date %}
      {% if k.cmp_id.cmp_id == j.cmp_id %}
      <td>{{k.created| naturaltime}}</td>
      <td>{{k.left| naturaltime}}</td>
      {% endif %}
      {% endfor %}
      
    </tr>
    {% endfor %} 
    {% endfor %}
  </tbody>
</table>
{% endblock %}

Ink/templates/Ink/profile1.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block body %}
<br>
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Company</th>
      <th scope="col">Joined</th>
      <th scope="col">Left</th>
    </tr>
  </thead>
  <tbody>
  	{% for i in history %}
    <tr>
      <td><a href="/compHome/{{i.cmp_id.company}}">{{i.cmp_id.company.first_name}}</a></td>
      <td>{{i.created| naturaltime}}</td>
      {% if i.left == None %}
        <td><b>Still Working</b></td>
      {% else %}
        <td>{{i.left| naturaltime}}</td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
<script type="text/javascript">
    var n=document.getElementById('1');
  console.log("yes");
  console.log(n);
  n.innerHTML="Create Company";
  n.setAttribute('href', '/createComp');

  var n=document.getElementById('2');
  console.log("yes");
  console.log(n);
  n.innerHTML="See Your Companies";
  n.setAttribute('href', '/ownComp');
  </script>
{% endblock %}

Ink/templates/Ink/type.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Register</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="icon" type="image/png" href={% static 'Ink/images/icons/favicon.ico' %} />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'Ink/vendor/bootstrap/css/bootstrap.min.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css"
	href={% static 'Ink/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css"
	href={% static 'Ink/fonts/iconic/css/material-design-iconic-font.min.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'Ink/vendor/animate/animate.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'Ink/vendor/css-hamburgers/hamburgers.min.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'Ink/vendor/animsition/css/animsition.min.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'Ink/vendor/select2/select2.min.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'Ink/vendor/daterangepicker/daterangepicker.css' %}>
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href={% static 'Ink/css/util.css' %}>
	<link rel="stylesheet" type="text/css" href={% static 'Ink/css/main.css' %}>
	<!--===============================================================================================-->
</head>

<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url('/static/Ink/images/bg-01.jpg');">
			<div class="wrap-login100">
				<form method="POST" action="/type/{{username}}">
					{% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>
					<span class="login100-form-title p-b-34 p-t-27">
						What Type Of User Are You??
					</span>
					<div class="container">
						<div id="div_id_name" class="form-group">
							<label for="id_name" class="control-label  requiredField">
								Username<span class="asteriskField">*</span> </label> 
								<div class="controls ">
									<input type="text" name="name" maxlength="150" autofocus="" class="textinput textInput form-control" required="" id="id_name" readonly=""> 
								</div>
							</div>
							<div id="div_id_typ" class="form-group">
								<label for="id_typ" class="control-label  requiredField">
									Typ<span class="asteriskField">*</span> </label> 
									<div class="controls ">
										<select name="typ" class="select form-control" id="id_typ">
											<option value="">----</option>
											<option value="employee">employee</option>
											<option value="company">company</option>
										</select>
									</div>
								</div>
								<div class="container-login100-form-btn">
									<button class="login100-form-btn">
										Submit
									</button>
								</div>
								<b>
									<div class="text-center p-t-40" style="font-size: 15px;">
										Developer :- Abhinav Sharma
										<a href="https://www.facebook.com/abhinav.sharma.16906" class="fa fa-facebook"></a>
									</div>
								</b>
							</div>
						</form>
					</div>
				</div>
			</div>

			<div id="dropDownSelect1"></div>

			<!--===============================================================================================-->
			<script src={% static 'Ink/vendor/jquery/jquery-3.2.1.min.js' %}></script>
			<!--===============================================================================================-->
			<script src={% static 'Ink/vendor/animsition/js/animsition.min.js' %}></script>
			<!--===============================================================================================-->
			<script src={% static 'Ink/vendor/bootstrap/js/popper.js' %}></script>
			<script src={% static 'Ink/vendor/bootstrap/js/bootstrap.min.js' %}></script>
			<!--===============================================================================================-->
			<script src={% static 'Ink/vendor/select2/select2.min.js' %}></script>
			<!--===============================================================================================-->
			<script src={% static 'Ink/vendor/daterangepicker/moment.min.js' %}></script>
			<script src={% static 'Ink/vendor/daterangepicker/daterangepicker.js' %}></script>
			<!--===============================================================================================-->
			<script src={% static 'Ink/vendor/countdowntime/countdowntime.js' %}></script>
			<!--===============================================================================================-->
			<script src={% static 'Ink/js/main.js' %}></script>

			<script type="text/javascript">
				document.getElementById('id_name').value="{{username}}";
			</script>
		</body>

		</html>